### ISSUE TITLE
[Feature Request]Add night/dark mode

### ISSUE THREAD

**Issue by rektpartyaftermath** [16arpi/Fox-RSS#15]
Really liked this app, but it seem to have no night/dark mode, would be perfect to add it.
Edit:
It seem to be already implemented? But my phone doesn't have global night mode.

**Comment by Lord-Valen** [comment]
It already follows the system theme, it just needs an option.

**Comment by rektpartyaftermath** [comment]
Yep, would be good to have an manual option for it.

**Comment by Lord-Valen** [comment]
As far as I can tell, this still isn't implemented.
