### ISSUE TITLE
Release on fdroid

### ISSUE THREAD

**Issue by Jrchintu** [16arpi/Fox-RSS#2]
Thanks for this awesome material design rss feed app. If possible, then I request developer to please release this app of fdroid store also (it's where many opensource android apps are)

https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by 16arpi** [comment]
Thanks! You can't imagine how many times I tried to put the app on fdroid but impossible to pass the tests :(
My « data » repository is there : https://gitlab.com/16arpi/fdroiddata/-/pipelines/465932527
I know the community can request app from other developers so yesss, if you find a way to put my app on fdroid I'll be more than grateful :)

**Comment by Bugaddr** [comment]
> 

Hey thanks for you'r reply 16arpi. Glad you knew about fdroid. I will try to search on few forums of fdroid if i can help you in the matter. Thanks for trying to release it on fdroid.

**Comment by 16arpi** [comment]
Update : I just [opened an issue](https://gitlab.com/fdroid/rfp/-/issues/2030) on the repository "Requests for packages" owned by fdroid. I hope they'll be able to help me.

So don't bother with all the forums and docs, unless you want to know how it works ^^

**Comment by Bugaddr** [comment]
> Update : I just [opened an issue](https://gitlab.com/fdroid/rfp/-/issues/2030) on the repository "Requests for packages" owned by fdroid. I hope they'll be able to help me.
> 
> So don't bother with all the forums and docs, unless you want to know how it works ^^

Cool, will be waiting for any news 👍

**Comment by Jrchintu** [comment]
Hey just saw the app on izzyondroid, thanks for release.

**Comment by 16arpi** [comment]
> Hey just saw the app on izzyondroid, thanks for release.

Wow, a nice person put it there ! Be careful, it's not the last version (1.8.2).

**Comment by Jrchintu** [comment]
> > Hey just saw the app on izzyondroid, thanks for release.
> 
> Wow, a nice person put it there ! Be careful, it's not the last version (1.8.2).

I think @izzysoft has put the app on izzyondroid fdroid repo. He is core maintainer of repo.

**Comment by IzzySoft** [comment]
Indeed I did. It was suggested to me, so part of the glory goes to the person who brought it to my attention :smile:

PS: I've send a link to forward your thanks. And 1.8.2 was just pulled today (updates are fetched automatically within 24h of becoming available here). Please take care to always increase `versionCode` when making a new release:

    WARNING com.pigeoff.rss_10.apk already exists but differs from the one downloaded

**Comment by Jrchintu** [comment]
> Indeed I did. It was suggested to me, so part of the glory goes to the person who brought it to my attention :smile:
> 
> PS: I've send a link to forward your thanks. And 1.8.2 was just pulled today (updates are fetched automatically within 24h of becoming available here). Please take care to always increase `versionCode` when making a new release:
> 
>     WARNING com.pigeoff.rss_10.apk already exists but differs from the one downloaded

Thanks izzy, your always there for help 😄👍

**Comment by 16arpi** [comment]
> Indeed I did. It was suggested to me, so part of the glory goes to the person who brought it to my attention :smile:
> 
> PS: I've send a link to forward your thanks. And 1.8.2 was just pulled today (updates are fetched automatically within 24h of becoming available here). Please take care to always increase `versionCode` when making a new release:
> 
>     WARNING com.pigeoff.rss_10.apk already exists but differs from the one downloaded

Aaah it's you ! Ok so the request was from me... Thanks !! 

Concerning versionCode, it is 11 in my gradle file (at least the one pushed on my github repository), why do you say the versionCode is still 10 ?

**Comment by IzzySoft** [comment]
My updater said so. And it got the `versionCode` from the APK. Maybe you adjusted in in `build.gradle` **after** you built the APK that is attached to the release? This is what `aapd d badging` gives on `rss-1.8.2.apk`:

    package: name='com.pigeoff.rss' versionCode='10' versionName='1.8.1' compileSdkVersion='31' compileSdkVersionCodename='12'

**Comment by 16arpi** [comment]
Alright, I'll double check my apk, gradle config and project :) thx!

**Comment by 16arpi** [comment]
Ok the APK is fixed, I messed up with my git branches locally.... my bad! It should be alright right now, tell me if something is weird.

**Comment by IzzySoft** [comment]
No error in the logs,  
But a new version of the :fox_face:  
So just for the dox:  
All fine in the box!

Thanks!

**Comment by Jrchintu** [comment]
Since the app is live, i consider closing this issue as fixed, thanks izzysoft & 16arpi

**Comment by IzzySoft** [comment]
@Bugaddr note that it's live only in my repo, not at f-droid.org – so you might want to go that extra mile (as requested originally by the author of this issue). Just saying, no complaints :wink: The :fox_face: is of course welcome to stay with my repo.

**Comment by Jrchintu** [comment]
> @Bugaddr note that it's live only in my repo, not at f-droid.org – so you might want to go that extra mile (as requested originally by the author of this issue). Just saying, no complaints :wink: The :fox_face: is of course welcome to stay with my repo.

Oh, for that @16arpi please tell me shall i keep issue on till you get app on f-droid.org ?

**Comment by 16arpi** [comment]
I think you can close it. I won't find a way to add it on the official fdroid repo. But if someone is motivated, please add it by yourself!

Thx you all for your help, it's very nice of you :)

**Comment by IzzySoft** [comment]
Let's see where your RFP is stuck… Oh. Waiting for someone making the MR. Hm. Let me raise visibility; I've just added the "ready" label (no idea why I forgot that last time), so a packager with a free slot on the search what to package is more likely to pick it. As it's pure Java/Kotlin, it shouldn't be too difficult, so maybe I could give it a try myself; if you promise to help me out should I run into build issues (of course only as far as it's related to your code and not our "build engine"), I'd do that. Chances are good it just goes smoothly, and no further help is needed.

**Comment by 16arpi** [comment]
> Let's see where your RFP is stuck… Oh. Waiting for someone making the MR. Hm. Let me raise visibility; I've just added the "ready" label (no idea why I forgot that last time), so a packager with a free slot on the search what to package is more likely to pick it. As it's pure Java/Kotlin, it shouldn't be too difficult, so maybe I could give it a try myself; if you promise to help me out should I run into build issues (of course only as far as it's related to your code and not our "build engine"), I'd do that. Chances are good it just goes smoothly, and no further help is needed.

If you can do it for me, yes please it'd be very nice ! I'm here if you get any bugs.

**Comment by jugendhacker** [comment]
@16arpi hi, I just worked on adding it to the official F-Droid repo. Could you pleases take a look on https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12058#note_1163977608

**Comment by 16arpi** [comment]
Hi @jugendhacker ! I got your message, I replied on gitlab :)

**Comment by jugendhacker** [comment]
@16arpi could you please take another look over on gitlab?
