### ISSUE TITLE
opml import

### ISSUE THREAD

**Issue by Toniozzzz** [16arpi/Fox-RSS#4]
Hi,

Amazing app to read in another way rss feed. My question is : is it possible to consider opml import in the next versions of Fox-RSS ? I have around a hundred of rss feed and i cannot import them one by one.

Once again great work 
Thanks
Antoine

**Comment by 16arpi** [comment]
Hi Antoine! Thx for you interest in my app :) I'll remember it. These days I don't have much time to work on new features but I'll try to think about it !!

If you have some knowledge in android development, perhaps you can try to implement it by yourself and ask for a merge request ? It'd be so nice to work together !

**Comment by Toniozzzz** [comment]
Unfortunately, i've no skills in android development. But i can wait for a future version. I hope a lot of people will use your app.

**Comment by 16arpi** [comment]
Alright, thx you very much for the support :)
