### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by bakinazik** [16arpi/Fox-RSS#5]
Does the app have a future to-do list? The most extraordinary rss reader I've ever seen, but it's missing a lot of features..

**Comment by 16arpi** [comment]
I'm glad you like and use the app! There's no to-do list, at least not public. The main priority is to make the app stable (there're still crashes and encoding issues). But please, tell me the features you'd like to be added, I'll keep them for later :)

**Comment by bakinazik** [comment]
1. Dark theme. I think it should have two options, black and dark, as it is impossible to set the dark theme to everyone's liking.
2. The names of the added feed links must be changeable. You know how obsessive people who usually use rss feeds are about it..
3. If the app doesn't offer all languages, you should create a project on a site like Crowdin and let people integrate their language into the app.

I've been using this app for about 3 weeks. These are the shortcomings that catch my eye.
And.. Thanks for asking my requests. ❤️

**Comment by 16arpi** [comment]
Yesss, great ideas! It's duly noted :)

**Comment by 16arpi** [comment]
Hello! So I pushed an update, v1.8.2, which add a dark mode and the possibility to change rss feed title when added.

Right now, title can be changed only when rss feed is added. I will put in a next update the possibility to change it afterwards. 

And for now, I won't let the community translate the app. If someone really whant to translate in its own langage, he/she can add a `string.xml` in the project and ask for a pull request.
