### ISSUE TITLE
Is Fox RSS still maintained?

### ISSUE THREAD

**Issue by Terkyz** [16arpi/Fox-RSS#6]
I just found this wonderful RSS Reader that makes reading RSS fun and addictive, but it lacks some features, and it hasn't been updated for a few months, is it still maintained?

**Comment by 16arpi** [comment]
Hello! Yes it is still maintained buuuuut I don't really have time these days to fully work on it :( Luckily, I'm about to push an update which add dark mode and the possibility to change the name of rss feeds when added.

Also, some people already asked for specific features, did you have some in mind ?

**Comment by Terkyz** [comment]
I would definitely suggest being able to import my RSS by .opml files and a widget capable of displaying a news summary

**Comment by 16arpi** [comment]
Alright! The opml import feature needs to be developed, I agree. For the widget, I don't know, it's not the main spirit of the app. If I develop it, it will be in a second time or if people join the project! Thanks for your feedback :)

**Comment by ccrowles** [comment]
> Alright! The opml import feature needs to be developed, I agree.

Hi, is the OPML import still planned? Asking because it's been 3 months since that reply, so maybe I'm dumb and I'm simply not seeing it

**Comment by 16arpi** [comment]
This project is still maintained but I'm not a professional developer, I'm still a student. I have plenty of more urgent projects to work on and unfortunately, I can't work on fox rss reader right now :(

**Comment by ccrowles** [comment]
That's very understandable, good luck with your studies!
